version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: selia-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=selia
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=selia
    networks:
      - selia-network
    restart: unless-stopped

networks:
  selia-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
